title: Project

files:
  sortable: true
  fields:
    caption:
      label: Caption
      type: textarea

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 3/4

  year:
    label: Year
    type:  text
    width: 1/4

  text:
    label: Text
    type:  textarea
